spring:
  application:
    name: kinesis-stock-producer

cloud:
  aws:
    inputstreamname: stock-input-stream
    credentials:
      accessKey: AKIA44JJ3DZVGUAWINOP
      secretKey: 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
    region: ap-south-1
    stack:
      auto: false

