version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "kdf-order-enhancer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-as8w3ao6uokq"
s3_prefix = "kdf-order-enhancer"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "KinesisStreamName=\"order-data-stream\""
image_repositories = []
disable_rollback = true
