AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  06-kinesis-order-enhancer

  Sample SAM Template for sam-java-app

Parameters:
  KinesisStreamName:
    Type: String

Resources:
  KinesisOrderEnhancerStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Ref KinesisStreamName
      ShardCount: 2

  OrdersEnhancerConsumerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: kdf-order-enhancer
      Handler: com.metaarivu.OrdersEnhancerConsumer::transformRecords
      Runtime: java8
      Timeout: 30
      MemorySize: 256
      Events:
        StreamRecordsBatch:
          Type: Kinesis
          Properties:
            Stream: !GetAtt KinesisOrderEnhancerStream.Arn
            BatchSize: 20
            MaximumBatchingWindowInSeconds: 30
            StartingPosition: TRIM_HORIZON
            MaximumRetryAttempts: 3
            Enabled: true
            BisectBatchOnFunctionError: true
