
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: stock-output-stream
          group: stock-output-stream-group
          content-type: text/plain

cloud:
  aws:
    credentials:
      accessKey: AKIA44JJ3DZVGUAWINOP
      secretKey: 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
    region:
      static: ap-south-1
    stack:
      auto: false
